CREATE TABLE IF NOT EXISTS `codes` (
  `ai` varchar(128) DEFAULT NULL,
  `ac` varchar(128) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `objects` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(128) NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `testtable` (
    `idt` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `namet` VARCHAR(128) NOT NULL DEFAULT '0',
    PRIMARY KEY (`idt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
